import { RawDataList } from '../dashboard/types/raw-data-from-mountain-project'

const dummyRawData: RawDataList = [
  {
    Date: '2023-01-15',
    Route: 'Route 1',
    Rating: '5.10a',
    Notes: 'Great climb',
    URL: 'http://example.com/route1',
    Pitches: '2',
    Location: 'Location A',
    'Avg Stars': '4',
    'Your Stars': '4',
    Style: 'Sport',
    'Lead Style': 'Onsight',
    'Route Type': 'Single Pitch',
    'Your Rating': '5.10a',
    Length: '60',
    'Rating Code': '510a',
    'Converted Grade': 5.1,
  },
  {
    Date: '2023-01-20',
    Route: 'Route 2',
    Rating: '5.10a',
    Notes: 'Great climb',
    URL: 'http://example.com/route1',
    Pitches: '2',
    Location: 'Location A',
    'Avg Stars': '4',
    'Your Stars': '4',
    Style: 'Sport',
    'Lead Style': 'Onsight',
    'Route Type': 'Single Pitch',
    'Your Rating': '5.10a',
    Length: '60',
    'Rating Code': '510a',
    'Converted Grade': 5.1,
  },
  {
    Date: '2023-02-20',
    Route: 'Route 3',
    Rating: '5.10b',
    Notes: 'Challenging crux',
    URL: 'http://example.com/route2',
    Pitches: '1',
    Location: 'Location B',
    'Avg Stars': '3',
    'Your Stars': '3',
    Style: 'Trad',
    'Lead Style': 'Flash',
    'Route Type': 'Sport',
    'Your Rating': '5.10b',
    Length: '100',
    'Rating Code': '510b',
    'Converted Grade': 5.1,
  },
  {
    Date: '2022-12-15',
    Route: 'Route 4',
    Rating: '5.9',
    Notes: 'Nice view',
    URL: 'http://example.com/route3',
    Pitches: '3',
    Location: 'Location C',
    'Avg Stars': '4.5',
    'Your Stars': '5',
    Style: 'Boulder',
    'Lead Style': 'Redpoint',
    'Route Type': 'Boulder',
    'Your Rating': '5.9',
    Length: '15',
    'Rating Code': '59',
    'Converted Grade': 5.9,
  },
  {
    Date: 'not-a-date',
    Route: 'Route 6 Invalid',
    Rating: 'N/A',
    Notes: 'Invalid date entry',
    URL: 'http://example.com/invalid',
    Pitches: 'N/A',
    Location: 'Unknown',
    'Avg Stars': '0',
    'Your Stars': '0',
    Style: 'N/A',
    'Lead Style': 'N/A',
    'Route Type': 'N/A',
    'Your Rating': 'N/A',
    Length: '0',
    'Rating Code': 'N/A',
    'Converted Grade': 0,
  },
]

export default dummyRawData
