import { Inter, DM_Sans } from 'next/font/google'


const inter = Inter({ 
  subsets: ['latin'] ,
  variable: '--font-inter',
  weight: '400'
})
const dmsans = DM_Sans({
  subsets: ['latin'],
  variable: '--font-dm-sans',
  weight: '400'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${inter.className} ${dmsans.className}`}>
      <body>{children}</body>
    </html>
  )
}
